scylladb/gocqlx

- gocqlx.go
- iterx.go
This pull request enables callers to force unsafe mode on iterx.
> iter: unsafe

- README.md
- example_test.go
- qb/cmp.go
- qb/cmp_test.go
- qb/token.go
- qb/token_test.go
This PR allows for use of functions in Cmp (i.e. WHERE clauses) and also introduces a helper for token based pagination.
> Cmp functions support in

- migrate/migrate.go
As discussed on #30 this is a separate PR with the two commits that provide feedback if no migration files were found or if no CQL statements were found in a migration file.
Thanks :)
> Provide feedback if no files or statements found

- go.mod
> generated an initial go.mod file.

- .travis.yml
- Makefile
Failed to integrate the service for scylladb repo, adding manually.
> added golangci: local download

- queryx.go
> queryx: added Iter function

- README.md
- example_test.go
- table/doc.go
- table/example_test.go
- table/table.go
- table/table_test.go
It adds support for super simple CRUD operations based on table schema model.
>  table: introduced table package

- qb/select.go
- qb/select_test.go
> qb: insert support order by multiple columns

- .golangci.yml
- go.mod
- go.sum
- qb/insert.go
- qb/insert_test.go
- qb/select.go
- qb/select_test.go
This adds a `Json()` method to the insert and select builders.
> Json support

- qb/cmp_test.go
- qb/delete_test.go
- qb/insert_test.go
- qb/select_test.go
- qb/update_test.go
- qb/value.go
The names are auto generated in the form param_0, param_1, ...
> qb: tuples now returns the correct names

- qb/token.go
- qb/token_test.go
fixes #111
This PR adds the token value compare functions to the `TokenBuilder` as discussed in #111
> add token value comparer to TokenBuilder

- qb/cmp.go
- qb/cmp_test.go
reference:
- https://github.com/scylladb/gocqlx/issues/114#issuecomment-550336062
Signed-off-by: Pierangelo Di Pilato <pierangelodipilato@gmail.com>
> Move ne comparator below eq comparator

- queryx.go
> Iterx inherit mapper from Queryx

- iterx.go
Assign unsafe from DefaultUnsafe and simplify condition.
> iterx: Refactor DefaultUnsafe handling

- .travis.yml
- Makefile
- Modernised Makefile
- Scylla and go bench run on separate CPUs
> makefile: moved running Scylla to makefile target

- iterx_test.go
- queryx_bench_test.go
- queryx_test.go
> Modernised tests

- queryx_test.go
> queryx: Add test to check that all methods are wrapped

- example_test.go
- iterx.go
- iterx_test.go
- queryx.go
Added ExecCAS and ExecCASRelease functions suitable for INSERT ... IF
NOT EXISTS and UPDATE's containing IF statement.
Functions returns information wheter query was applied or not.
Fixes #98
> queryx: Added CAS exec functions (#98)

- benchmark_test.go
- doc_test.go
- example_test.go
- gocqlxtest/gocqlxtest.go
- iterx_test.go
- migrate/callback.go
- migrate/migrate.go
- migrate/migrate_test.go
- queryx_bench_test.go
- table/table.go
- table/table_test.go
> Update tests to use v2

- table/table.go
> Correctly state in the GetQuery comment that it gets by primary key

- README.md
I mean... It's time... Time to finally update it.
> Update godoc badge link

- README.md
For https://github.com/scylladb/gocqlx/issues/225
> update documentation with examples of non-persisted fields

- queryx.go
> queryx: add note to ExecCAS docs

- .github/workflows/main.yml
- Makefile
Aims to hotfix https://github.com/scylladb/gocqlx/issues/232 for gihub CI pipeline, will be squashed and signed on approval
> Update GH actions

- .github/workflows/main.yml
> Bump scylla version and add a linter to the CI

- batchx.go
- batchx_test.go
It is continuation of https://github.com/scylladb/gocqlx/pull/252
> Add additional methods to Batch similar to what exists on Queryx

- table/table.go
- table/table_test.go
Hi,
In this PR, we add a new function to return the SelectBuilder for the table Get operation.
Thank you
> expose SelectBuilder for table Get operation

- README.md
> adding lesson link to readme file

- cmd/schemagen/schemagen.go
Reincarnation of https://github.com/scylladb/gocqlx/pull/255
> Add --query-timeout and --connection-timeout options
