- benchmark_test.go
- example_test.go
- qb/delete.go
- qb/delete_test.go
- qb/expr.go
- qb/insert.go
- qb/insert_test.go
- qb/update.go
- qb/update_test.go
- qb/utils.go
- qb/utils_test.go
- queryx.go
- queryx_test.go
With this PR builders `TTL` and  `Timestamp` methods will generate a named parameter. `qb` provides helper methods to generate proper values from `time.Duration` and `time.Time` respectively. `Queryx` gains new method `BindStructMap` that acts like `BindStruct` but can fallback to a map when missing values.
> Named parameters for USING TTL and TIMESTAMP

- example_test.go
- iterx.go
Releasing query objects in Get/Select could easily lead to
double-releases, which can cause dangerous and tricky data races.
> Do not release queries in Get/Select. Fix #25.

- queryx.go
This speeds up binding structs by using the new TraversalsByNameFunc introduced in jmoiron/sqlx#358, which avoids allocating a slice.
```
name          old time/op    new time/op    delta
BindStruct-8     519ns ± 2%     400ns ± 2%  -22.97%  (p=0.000 n=10+10)
name          old alloc/op   new alloc/op   delta
BindStruct-8      224B ± 0%      128B ± 0%  -42.86%  (p=0.000 n=10+10)
name          old allocs/op  new allocs/op  delta
BindStruct-8      3.00 ± 0%      2.00 ± 0%  -33.33%  (p=0.000 n=10+10)
```
> Avoid one allocation when binding structs

- qb/select.go
- qb/select_test.go
Clients could do this hackily before by manually passing "col AS name",
but it isn't clearly supported.
> Add ColumnAs for 'SELECT col AS name' queries.

- migrate/migrate.go
Tinyint is not supported on scylla enterprise.
> migrate: replace tinyint with int

- README.md
- qb/cmp.go
- qb/cmp_test.go
- qb/insert.go
- qb/insert_test.go
- qb/token.go
- qb/update.go
- qb/update_test.go
- qb/value.go
The 'value' interface represents a CQL value for use in a comparison,
update, or intitialization operation. A consistent interface for this
allows us to easily support specifying default-named, custom-named,
literal, and evaluated-function values in all these contexts.
Parameters to Func should probably also be values to support full
composition, but that would be a breaking change because Func's
properties are exposed.
The value interface could itself be exposed if we wanted to allow
clients to pass their own values to SetValue, etc, but for now it is a
package-internal abstraction.
> Support for literals in INSERT and UPDATE and comparisons

- migrate/callback.go
- migrate/migrate.go
Callback enables interrupting the migration process and executing code
while migrating.
> migrate: migration callbacks

- Makefile
- gocqlx.go
- iterx.go
- mapper.go
- queryx.go
- reflectx/README.md
- reflectx/reflect.go
- reflectx/reflect_test.go
Depending on sqlx makes users pull SQL related code that is usually not
needed. Tools like dep make it easier by explicitly listing relevant
subpackages but the code needs to be downloaded anyway.
> Remove sqlx dependency

- qb/cmp.go
- qb/cmp_test.go
This is needed to query the keys of a map using a secondary index like this:
CREATE TABLE user (id uuid primary key, cities map<text, text>);
CREATE INDEX foobar ON user (keys(cities));
SELECT * FROM user WHERE cities CONTAINS KEY 'Paris'
> Add qb.ContainsKey to query keys in a map

- queryx.go
> CompileNamedQuery: fix doc string to include escaping ::

- qb/select.go
- qb/select_test.go
- qb/utils.go
* In qb/select.go, if there are no colums and the query have a GroupBy
statement then the query will be malformated.
* In qb/utils.go, refactor writeCql with a strings.Join call.
[Issue #69](https://github.com/scylladb/gocqlx/issues/69)
> fix(qb): Fixed group by generation

- go.mod
Due to gocql's issue (ex. https://github.com/gocql/gocql/issues/1191), the current version of gocqlx takes too high CPU utilization.
We updated go.mod file to use the newest version of gocql.
Thanks.
> Update gocql version

- queryx_wrap.go
> queryx: wrap all the gocql.Query methods that return *Query to return *Queryx

- queryx_wrap.go
fix gocql.Query.WithContext retrun shallow copy bug
> fix gocql.Query.WithContext retrun shallow copy bug

- qb/cmp.go
- qb/cmp_test.go
- qb/delete_test.go
- qb/insert.go
- qb/insert_test.go
- qb/select_test.go
- qb/update.go
- qb/update_test.go
- qb/value.go
This adds tuple support to `qb`. It adds a number of versions of the comparators and builder primitifes that emit placeholders.
> Tuple support

- .travis_start_db.sh
- iterx.go
- iterx_test.go
We used to rely upon NumRows to determine if there are
new pages available. This is not correct and the needed
data to do this is not exposed by the gocql driver.
We simply remove these checks and let the driver decide.
> iterx: paging iteration working

- qb/select.go
- qb/select_test.go
This commit adds support for BYPASS CACHE extension that is present in
ScyllaDB since 3.1 / 2019.1.1.
https://docs.scylladb.com/getting-started/dml/#bypass-cache
> Add support for BYPASS CACHE

- qb/cmp.go
- qb/cmp_test.go
The `qb.Cmp` lacks `not equal` methods related to the operator `!=`
even though the documentation
https://docs.scylladb.com/getting-started/dml/#select-statement mentions
it.
Closes: #114
Signed-off-by: Pierangelo Di Pilato <pierangelodipilato@gmail.com>
> Add not equal comparators (!=)

- .gitignore
- qb/select.go
- qb/select_bench_test.go
- qb/token.go
- qb/update.go
Changed some core functions to avoid extra allocation performed during assigment, for instance:
Instead of recreate the slice in this way:
```
// Columns adds result columns to the query.
func (b *SelectBuilder) Columns(columns ...string) *SelectBuilder {
b.columns = append(b.columns, columns...)
return b
}
```
we can forwad it:
```
// Columns adds result columns to the query.
func (b *SelectBuilder) Columns(columns ...string) *SelectBuilder {
if len(b.columns) == 0 {
b.columns = columns
} else {
b.columns = append(b.columns, columns...)
}
return b
}
```
> Improve assign in qb package

- iterx.go
- iterx_test.go
As discussed in #130 here's a simple option to enable Iterx's `Unsafe()` behavior globally.
> Add DefaultUnsafe global

- iterx_test.go
Small issue I thought I fixed in an amend in #131. 🤦‍♂  But it was merged quicker than I could push. 😬
> Fix resetting DefaultUnsafe option after the DefaultUnsafe select test

- go.mod
- go.sum
- migrate/migrate.go
This uses `(*gocql.Session).AwaitSchemaAgreement` before applying each CQL statement in a migration (see https://github.com/gocql/gocql/issues/1301).
It's marked as a draft for discussion as well as because it's still waiting on https://github.com/gocql/gocql/pull/1395 to be merged and is currently using our fork of gocql.
> Await schema agreement during migrations

- table/table.go
- table/table_test.go
When table is used with `SelectBuilder` it triggers data race on `Where` condition usage.
This PR copies underlining slices on table creation to allow safe concurrent usage of the table.
> table: fix data race in select builder usage

- table/table.go
- table/table_test.go
I'd like to add some public functions to expose CRUD query builders,  which is similar as
func (t *Table) SelectBuilder(columns ...string) *qb.SelectBuilder {
to enable timestamp at the granularity of batch statements.
> gocqlx/table/Table: support timestamp at the granularity of batch statements

- benchmark_test.go
- doc_test.go
- example_test.go
- gocqlxtest/gocqlxtest.go
- iterx.go
- iterx_test.go
- mapper.go
- migrate/callback.go
- migrate/migrate.go
- migrate/migrate_test.go
- queryx.go
- session.go
- table/example_test.go
With this patch we can now use gocqlx like:
```
session.Query(`SELECT * FROM struct_table`, nil).Get(&v)
```
instead of (old format):
```
gocqlx.Query(session.Query(`SELECT * FROM struct_table`), nil).Get(&v)
```
> Add Session wrapper

- qb/batch.go
- qb/delete.go
- qb/insert.go
- qb/select.go
- qb/update.go
- table/table.go
These shortucuts allows to write shorter more straightforward code.
It allows to write:
```
clusters.InsertQuery(session).BindStruct(r).ExecRelease()
qb.Select("cluster").Columns("id").Query(session)
```
instead of:
```
session.Query(clusters.Insert().ToCql()).BindStruct(r).ExecRelease()
session.Query(qb.Select("cluster").Columns("id").ToCql())
```
> Added shortcuts to Queryx

- Makefile
- README.md
- example_test.go
- gocqlxtest/gocqlxtest.go
- migrate/README.md
- migrate/callback.go
- migrate/doc.go
- migrate/example/example_test.go
- migrate/example/migrations/m1.cql
- migrate/export_test.go
- migrate/migrate.go
- migrate/migrate_test.go
This patch adds a new migration event type InMigration that it triggered by adding `-- DO <name>;` comment in a CQL file.
Fixes #101
> migrate: Add support for Go code migrations in the middle of processing a CQL file

- qb/limit.go
- qb/select.go
- qb/select_test.go
> qb: add named limit and per partition limit clauses

- Makefile
- benchmark_test.go
- dbutil/rewrite_test.go
- example_test.go
- iterx_test.go
- migrate/migrate_test.go
- queryx.go
- queryx_test.go
- session.go
- transformer.go
> queryx: unset empty values

- gocqlxtest/gocqlxtest.go
```
go help testflag
```
> The 'go test' command may run tests for different packages
> 	    in parallel as well, according to the setting of the -p flag
> 	    (see 'go help build').
In parallel execution there will be a collision with single database name
> Added test database name flag

- qb/cmp.go
- qb/cmp_test.go
- qb/delete_test.go
- qb/insert_test.go
- qb/select_test.go
- qb/update_test.go
- qb/value.go
I found no other way to 
```
sometable.SelectBuilder(colSomeCol).
Where(qb.GtOrEqTupleNamed(colCreatedAtID, 2, "start")).
Where(qb.LtTupleNamed(colCreatedAtID, 2, "end")).
```
i.e. do specify a range scan on a tuple column with both ends of the range given. With only `qb.GtOrEqTuple` and `qb.LtTuple` the autogenerated names are both derived from the column name and collide, thus it is not possible to specify different ends for the range.
Before merging this, please also consider that tuple-element syntax has some conflict with `gocql`, which produces `"col[0]"` in `SliceMap`, and not `"col_0"` as gocqlx wants it during tuple binding.
Some options I see:
* Rename this PR's functions (or add yet more) with `<Cmp>TupleIdx` resp. `<Cmp>TupleIdxNamed` which autogenerate `gocql` compatible …
> Add <Cmp>TupleNamed for two-sided range-queries on tuples

- queryx.go
... otherwise the [applied] column is not noticed and setting of `Iterx.applied` is skipped. I'm not sure whether this is the right fix, to be honest; it seems a bit too ad-hoc.
Anyway, we noticed that after
```
applied, err := session.Query(table.InsertBuilder().Unique().ToCql()).BindStruct(data).ExecCASRelease()
```
`applied` would always be `false`, even if the LWT was in fact applied. Ultimately, this was due to no metadata being present in the iterator, thus Iterx.structScan not finding the `[applied]` column. The commit in this PR fixes that by forcing metadata retrieval for the two CAS methods, _but_ both from the timeline of the commits in `gocql` and `gocqlx` and from the testsuite of `gocqlx` this seems like it should actually work without this PR.
... which is due to the CI …
> Force metadata retrieval for CAS queries

- qb/select.go
- qb/select_test.go
Looking at the select statement specification [here](https://docs.scylladb.com/getting-started/dml/#select-statement),
it seems the USING clause should be at the end of the statement.
> fix using timeout order in select stmt

- cmd/schemagen/schemagen.go
This PR adds user and password flags to schemagen. We needed this to generate table models for a Cassandra/Scylla that is password-protected. I manually tested it.
> add user password authentication to schemagen

- cmd/schemagen/keyspace.tmpl
- cmd/schemagen/map_types.go
- cmd/schemagen/map_types_test.go
- cmd/schemagen/schemagen.go
- cmd/schemagen/schemagen_test.go
- cmd/schemagen/testdata/models.go.txt
- example_test.go
- go.mod
- go.sum
Code generation for table structs
> Structs tables

- table/table.go
In https://github.com/scylladb/gocqlx/pull/190 I forgot to update the comment of `GetQueryContext` as well. This PR fixes this.
> Fix GetQueryContext method comment

- iterx.go
- iterx_test.go
- queryx.go
- session.go
- udt.go
We can't return an error in case a field is added to the UDT, otherwise existing code would break by simply altering the UDT in the database. For extra fields at the end of the UDT put nulls to be in line with gocql, but also python-driver and java-driver.
In gocql it was fixed in https://github.com/scylladb/gocql/commit/d2ed1bb74f3118a83a352e9ce912be765001efa4
java-driver https://github.com/datastax/java-driver/blob/ef56d561d97adcae48e0e6e8807f334aedc0d783/core/src/main/java/com/datastax/oss/driver/internal/core/type/codec/UdtCodec.java#L86
python-driver: https://github.com/datastax/python-driver/blob/15d715f4e686032b02ce785eca1d176d2b25e32b/cassandra/cqltypes.py#L1036
> Marshal missing UDT fields as null instead of failing

- example_test.go
- iterx.go
- iterx_test.go
- queryx.go
- session.go
- udt.go
Previously by default the presence of a missing field in a udt would result in an error reported. The Unsafe mechanism could be used to ignore these fields.
This PR changes the default behavior to ignoring missing fields and only reporting an error if Strict mode is used. This approach is in line with the gocql. 
This is a breaking change and the major release will be needed.
Refs: #269
> Replace Unsafe with Strict mechanism

- .github/workflows/main.yml
- Makefile
Currently `Makefile` uses `SCYLLA_VERSION` to define docker image.
Switching to `SCYLLA_IMAGE` instead will help to target enterprise, nightly or custom image
> Switch to use scylla image instead of scylla version, to be able to target enterprise

- migrate/migrate.go
- migrate/migrate_test.go
Fixed a couple of error messages for migrate.go
The inconsistent migration error incorrectly swaps the migration names
1. Create a migration file named `0.0.1-set-up-tables.cql`
2. Run the migrations via `gocqlx.Migrate`
3. Rename the migration file to `0.0.1-set-up-tables-RENAMED.cql`
4. Run the migrations again
```
stderr: panic: inconsistent migrations found, expected "0.0.1.set-up-tables-RENAMED.cql" got "0.0.1.set-up-tables.cql" at 1
```
should instead be
```
stderr: panic: inconsistent migrations found, expected "0.0.1.set-up-tables.cql" got "0.0.1.set-up-tables-RENAMED.cql" at 1
```
> Update migration error messages

- qb/update.go
- qb/update_test.go
Previously it was only possible to use `AllowFiltering()` on the select query builder.
This PR adds the option to add `ALLOW FILTERING` to the update query.
Fixes: #288
> Add option to add ALLOW FILTERING to the update query

- migrate/example/example_test.go
- migrate/migrate.go
- migrate/migrate_test.go
This PR adds a `Pending` function to the `package migration`.
Can be used to ensure that an application is up to date before launching.
> feat(migrate): add `Pending` function for pending migrations

- README.md
Reincarnation of https://github.com/scylladb/gocqlx/pull/268
After `gocqlx` switched to `scylladb/gocql` driver due to the presence `replace` dirrective in `go.mod` user can't ue `go install` anymore.
> Update README.md schemagen installation and usage

- cmd/schemagen/schemagen.go
Reincarnation of https://github.com/scylladb/gocqlx/pull/258
> Add schemagen ssl options

- qb/using.go
- qb/using_test.go
- qb/utils.go
- qb/utils_test.go
Scylla does not support fractions.
Currently following code: `Timeout(time.Second + 100*time.Millisecond)` will result in `USING TIMEOUT 1.1s`, which does not match what scylla expects and it fails.
We need to make sure that time is formatted the following way: `XmYsZms`
Fixes: https://github.com/scylladb/gocqlx/issues/298
> Fix USING TIMEOUT time generation

- gocqlxtest/gocqlxtest.go
- queryx_wrap.go
This pull request includes changes to improve the resilience and robustness of the `gocqlx` library by adding reconnection policies and handling `nil` contexts. The most important changes include the addition of a constant reconnection policy in the `CreateCluster` function and the handling of `nil` contexts in the `WithContext` method.
Improvements to resilience and robustness:
* [`gocqlxtest/gocqlxtest.go`](diffhunk://#diff-f1e07c9ab4b35901f3194ab930c220a948a03828320be2cccfccd9afe83bea47R54-R57): Added a constant reconnection policy to handle reconnections with a maximum of 10 retries and a 3-second interval between retries in the `CreateCluster` function.
* [`queryx_wrap.go`](diffhunk://#diff-5d5f79db7be74fe022c69112a825b39532ce7830002f78dfd2ac163030812813R89-R91): Modified the …
> Enhance cluster configuration with reconnection policy and improve code

- cmd/schemagen/schemagen.go
At the moment, generated file has permissions `0777` (i.e read/write/execute for user, group, and others). It is not critical issues but makes some inconvenience in bootstraping initial database schema. This pull request fixes this issue.
> Adjust permissions of output file and directory

- .github/workflows/main.yml
- Makefile
- qb/update.go
Updating tools is not easy due to the bad Makefile design
Make it easier to update tools, preparing to golang and gocql update.
> Refactor Makefile tools installation

- .github/workflows/main.yml
- Makefile
- cmd/schemagen/schemagen_test.go
- cmd/schemagen/testdata/go.mod
- go.mod
- migrate/migrate.go
Does the following:
1. Update golang on both `go.mod` files to `1.20`
2. Updates workflow to make it work on golang `1.20`
3. Fixes problem with depricated `ioutils` pacakge.
> Update golang to 1.20

- batchx.go
- batchx_test.go
- queryx_test.go
Some of `gocql.Batch` APIs are not present in the `gocqlx.Batch`. 
We need to have them implemented and have a test to make sure no API has forgotten.
> Add missing batch API

- cmd/schemagen/keyspace.tmpl
- cmd/schemagen/schemagen.go
- cmd/schemagen/schemagen_test.go
- cmd/schemagen/testdata/no_ignore_indexes/models.go
Related to #320.
This PR is the final piece in restoring backward compatibility with `schemagen@v2`. It adds generation of index models with some tests specific to this case. Also, it fixes minor issues and makes generated source file a little bit prettier.
> Bring back index model generation

- queryx_bench_test.go
This panic caused by `Queryx` struct having no `Mapper` and no `gocql.Query` in it.
> Fix panic in tests in queryx_bench_test.go

- README.md
- batchx.go
- cmd/schemagen/testdata/go.mod
- cmd/schemagen/testdata/go.sum
- go.mod
- go.sum
- queryx.go
gocql 1.15.3 brings new APIs for `gocql.Batch` and `gocql.Query`:
- `SetRequestTimeout`
- `GetRequestTimeout`
So, this change adds relative APIs to the `gocqlx.Batch` and `gocqlx.Queryx`.
> Upgrade gocql to 1.15.3
